// Public API for the Synthetic World Playground.
//
// This is the whole thesis of the accompanying blog post in miniature: a record
// is not generated by prose. It's assembled from structured decisions (the
// modifiers), and only then rendered into a prompt and a sample artifact. Same
// seed -> same decisions -> same world; re-roll the seed and you get a
// completely different one, without touching the "text" step at all.

import type { EntityDefinition, Generation, Modifiers } from './types';
import { entities, getEntityDefinition, entityIndex } from './registry';
import { mulberry32, randomSeed, nextSeed, pickModifiers, generationIdFrom } from './random';

export type { EntityDefinition, Generation, Modifiers, ModifierDef, SampleOutput } from './types';

/** Every entity definition, for building menus / tabs in the UI. */
export function getEntities(): EntityDefinition[] {
    return entities;
}

/** The raw prompt template (with {{placeholders}}) for one entity. */
export function renderPromptTemplate(entityId: string): string {
    return getEntityDefinition(entityId).promptTemplate;
}

/** Fill an entity's prompt template with a supplied set of modifier values. */
export function renderFilledPrompt(entityId: string, modifiers: Modifiers): string {
    return getEntityDefinition(entityId).buildPrompt(modifiers);
}

/**
 * Deterministically build a full generation from an explicit seed. The same
 * (entityId, seed) pair always yields an identical `Generation` — the
 * reproducible-facts guarantee.
 */
export function generateEntityWithSeed(entityId: string, seed: number): Generation {
    const entity = getEntityDefinition(entityId);
    const rng = mulberry32(seed);
    const modifiers = pickModifiers(rng, entity.modifiers);
    return {
        entity,
        modifiers,
        promptTemplate: entity.promptTemplate,
        filledPrompt: entity.buildPrompt(modifiers),
        sampleOutput: entity.buildSample(modifiers),
        generationId: generationIdFrom(entityId, seed),
    };
}

// --- Stateful convenience layer -------------------------------------------
//
// `rootSeed` is chosen once when this module is first imported. In the browser
// that means "once per page load", so a refresh produces a fresh set of
// examples. Each entity tracks its own current seed so regeneration can advance
// independently.

const rootSeed = randomSeed();
const currentSeed = new Map<string, number>();

function seedFor(entityId: string): number {
    let seed = currentSeed.get(entityId);
    if (seed === undefined) {
        // Derive a distinct starting seed per entity from the page-load root.
        seed = nextSeed((rootSeed + entityIndex(entityId) * 0x9e3779b1) >>> 0);
        currentSeed.set(entityId, seed);
    }
    return seed;
}

/** Generate (or return the current) example for an entity using its live seed. */
export function generateEntity(entityId: string): Generation {
    return generateEntityWithSeed(entityId, seedFor(entityId));
}

/**
 * Re-roll an entity: advance its seed, pick new values for the *same* modifier
 * keys, and rebuild the filled prompt and sample. The modifier keys are fixed
 * by the entity definition, so regeneration only ever changes values.
 */
export function regenerateEntity(entityId: string): Generation {
    const seed = nextSeed(seedFor(entityId));
    currentSeed.set(entityId, seed);
    return generateEntityWithSeed(entityId, seed);
}
